server:
  port: 8081
  servlet:
    context-path: /authman
spring:
  mvc:
    static-path-pattern: /**
    thymeleaf:
      encoding: UTF-8
      cache: false
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/authman?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
